@startuml "next-context"
!include ../C4_Context.puml

title "Умный дом"

top to bottom direction

Person(support, "Техподдержка", "Инженер умного дома")
Person(user, "Пользователь", "Владелец умного дома")
System(system, "Тёплый дом", "Система управления датчиками и другими устройствами")

System_Ext(sensor, "Датчик", "Позволяет определить простые параметры, такие как температура, освещенность и т.д.")
System_Ext(device, "Управляющее устройство", "Может включить/выключить или послать команду в устройство отопления, света, замка и т.д.")
System_Ext(camera, "Камера", "Видеонаблюдение")
System_Ext(payment, "Платежная система", "Проводит платежи")

Rel(user, system, "Управляет своим умным домом")
Rel(system, sensor, "Получает данные")
Rel(system, device, "Управляет устройствами")
Rel(system, camera, "Просматривает видеопоток")
Rel(system, payment, "Получает информацию о проведенных платежах")
Rel(user, payment, "Оплачивает подписку")
Rel(support, system, "Выполняет поддержку пользователей")

@enduml