spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=legacy-adapter
spring.kafka.consumer.auto-offset-reset=earliest

legacy.adapter.smart-home-url=http://smart_home:8080

legacy.adapter.kafka.topic.temperature-commands=temperature-commands
legacy.adapter.kafka.topic.temperature-updates=temperature-updates
